= Ansible Collection - nickhardiman.vm_satellite

== Use roles

The example playbooks run these roles.

* nickhardiman.vm_satellite.build
* nickhardiman.vm_satellite.configure_os
* nickhardiman.vm_satellite.install_app
* nickhardiman.vm_satellite.configure_app

== Use playbooks

Create a Red Hat Satellite VM.

----
ansible-playbook --vault-pass-file=~/my-vault-pass --extra-vars=@~/vault-credentials.yml nickhardiman.vm_satellite.build_vm.yml
ansible-playbook --vault-pass-file=~/my-vault-pass --extra-vars=@~/vault-credentials.yml nickhardiman.vm_satellite.configure_os.yml
ansible-playbook --vault-pass-file=~/my-vault-pass --extra-vars=@~/vault-credentials.yml nickhardiman.vm_satellite.install_app.yml
ansible-playbook --vault-pass-file=~/my-vault-pass --extra-vars=@~/vault-credentials.yml nickhardiman.vm_satellite.configure_app.yml
----

Shell scripts in https://github.com/nickhardiman/script-rhel-setup create files my-vault-pass and vault-credentials.yml.

Ansible roles in https://github.com/nickhardiman/ansible-collection-libvirt create the hypervisor.


== add an IP route to workstation

The workstation does not know about the private LAN.
Add a route to allow a playbook running on the control node to SSH to the new managed node. 
See 
https://github.com/nickhardiman/script-rhel-setup/blob/main/libvirt-utils/macos-route-add.sh
for one way of doing this. 

Yet another refactor of my home lab automation

== third attempt, RHEL lab 

WIP

Build a network of virtual machines on one fresh RHEL 10 host.

Yet another refactor of my home lab automation. 

Take the AAP2 work (ansible-playbook-aap-lab) and break up into less chokingly massive chunks.

* https://github.com/nickhardiman/script-rhel-setup
* https://github.com/nickhardiman/ansible-playbook-rhel-lab
* https://github.com/nickhardiman/ansible-collection-platform
* https://github.com/nickhardiman/ansible-collection-libvirt
* https://github.com/nickhardiman/ansible-collection-vm-gateway
* https://github.com/nickhardiman/ansible-collection-vm-satellite


== second attempt, AAP2 refarch

couple years ago

network of virtual machines on three fresh RHEL 9 hosts.

worked, but an absolute monster 

* https://github.com/nickhardiman/ansible-playbook-aap-lab
* https://github.com/nickhardiman/ansible-collection-platform

== first attempt, RHEL lab

few years ago 

network of virtual machines on three fresh RHEL 9 hosts.

* https://github.com/nickhardiman/ansible-playbook-source
* https://github.com/nickhardiman/ansible-playbook-build
* https://github.com/nickhardiman/ansible-playbook-supply
* https://github.com/nickhardiman/ansible-collection-platform
* https://github.com/nickhardiman/ansible-collection-app
