---
# manual configure
# https://satellite/ > Configure > Host Groups > Create Host Group > Host Group
# web UI https://satellite/hostgroups
# collection docs
# module (describes fields)
# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/module/hostgroup
# role
# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/hostgroups
#   was https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/hostgroups/

# root_pass and nolog
# Role
# collections/ansible_collections/redhat/satellite/roles/hostgroups/tasks/main.yml
# sets nolog: true if root_pass is defined

satellite_hostgroups:
  - 
    name: "hg-rhel-8"
    organization: '{{ satellite_organization }}'
    description: "RHEL 8 hostgroup"
    lifecycle_environment: 'lce-build'
    content_view: 'cv-rhcdn-base-rhel-8'
    content_source: '{{ inventory_hostname }}'
    openscap_proxy: '{{ inventory_hostname }}'
    # console > Configure > Host Groups > Create Host Group > Network
    domain: 'silvan.uk'
    subnet: 'sn-lab-subnet'
    # console > Configure > Host Groups > Create Host Group > Operating System
    architecture: "x86_64"
    operatingsystem: "RedHat 8.10"
    kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10'
    ptable: "Kickstart default"
    # libvirt+UEFI provision only works if this is set to None
    pxe_loader: 'None'
    # pxe_loader: 'PXELinux BIOS'
    root_pass: 'Password;1'
    # console > Configure > Host Groups > Create Host Group > Locations, Organizations, Activation Keys
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"
    activation_keys: ak-build-rhel-8
  -
    name: "hg-rhel-9"
    organization: '{{ satellite_organization }}'
    description: "RHEL 9 hostgroup"
    lifecycle_environment: 'lce-build'
    content_view: 'cv-rhcdn-base-rhel-9'
    content_source: '{{ inventory_hostname }}'
    openscap_proxy: '{{ inventory_hostname }}'
    # console > Configure > Host Groups > Create Host Group > Network
    domain: 'silvan.uk'
    subnet: 'sn-lab-subnet'
    # console > Configure > Host Groups > Create Host Group > Operating System
    architecture: "x86_64"
    operatingsystem: "RedHat 9.4"
    kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4'
    # operatingsystem: "RHEL 9.7"
    # kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.7'
    ptable: "Kickstart default"
    pxe_loader: 'PXELinux BIOS'
    root_pass: 'Password;1'
    # console > Configure > Host Groups > Create Host Group > Locations, Organizations, Activation Keys
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'
    activation_keys: ak-build-rhel-9
  -
    name: "hg-rhel-10"
    organization: '{{ satellite_organization }}'
    description: "RHEL 10 hostgroup"
    lifecycle_environment: 'lce-build'
    content_view: 'cv-rhcdn-base-rhel-10'
    content_source: '{{ inventory_hostname }}'
    openscap_proxy: '{{ inventory_hostname }}'
    # console > Configure > Host Groups > Create Host Group > Network
    domain: 'silvan.uk'
    subnet: 'sn-lab-subnet'
    # console > Configure > Host Groups > Create Host Group > Operating System
    architecture: "x86_64"
    operatingsystem: "RedHat 10.1"
    kickstart_repository: 'Red Hat Enterprise Linux 10 for x86_64 - BaseOS Kickstart 10.1'
    ptable: "Kickstart default"
    pxe_loader: 'PXELinux BIOS'
    root_pass: 'Password;1'
    # console > Configure > Host Groups > Create Host Group > Locations, Organizations, Activation Keys
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'
    activation_keys: ak-build-rhel-10
