---
# so very many to include
# https://github.com/nickhardiman/ansible-playbook-aap-lab/blob/main/aap-lab-playbook%F0%9F%98%8E.yml

# - ansible.builtin.import_playbook: playbooks/satellite-content-add.yml
# - ansible.builtin.import_playbook: playbooks/satellite-infrastructure-add.yml
# - ansible.builtin.import_playbook: playbooks/satellite-configure-add.yml

# https://satellite/ > Administer > Settings > Content > Default HTTP Proxy
# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/settings

# Vile workaround for crap var scope and passing
- name: Include vars from satellite config directory
  ansible.builtin.include_vars:
    dir: satellite-config
    ignore_files: []
    extensions: ["yml"]

# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/$ROLE
# $ROLE is settings, manifest, repositories, lifecycle_environments, etc. 
- name: "Add roles that don't need extra vars"
  ansible.builtin.include_role:
    name: "{{ l_role }}"
  loop:
    - redhat.satellite.manifest                # see variables satellite_manifest_*
    - redhat.satellite.repositories            # see variable satellite_products
    - redhat.satellite.lifecycle_environments  # see variable satellite_lifecycle_environments
    - redhat.satellite.content_views           # see variables satellite_organization and satellite_content_views
    - redhat.satellite.content_view_publish    # also uses satellite_content_views
    - redhat.satellite.activation_keys         # see variable satellite_activation_keys
  loop_control:
    loop_var: l_role

# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/module/repository_sync/
# better to wait or to do as async background job?
# https://github.com/sscheib/ansible_satellite/blob/main/07_satellite_sync_repositories.yml
- name: "Sync all repositories in each product"
  redhat.satellite.repository_sync:
    server_url:   "{{ satellite_server_url }}"
    username:     "{{ satellite_username }}"
    password:     "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    product: "{{ item }}"
  loop: "{{ satellite_products | map(attribute='name') | unique }}"

  # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/module/sync_plan/
  # usng a dynamically set date (relative to now) means this is always changed, never OK (unchanged). 
- name: "Create daily sync plan for all products"
  redhat.satellite.sync_plan:
    server_url:   "{{ satellite_server_url }}"
    username:     "{{ satellite_username }}"
    password:     "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    name: "Daily Sync"
    interval: "daily"    #  hourly, daily, weekly, custom cron
    enabled: true
    # sync_date: "{{ lookup('ansible.builtin.pipe', 'date +\"%Y-%m-%d %H:%M:%S %Z\"') }}"  # now
    # sync_date: "2017-01-01 00:00:00 UTC" # fixed date
    sync_date: "{{ lookup('ansible.builtin.pipe', 'date +\"%Y-%m-%d 10:00:00 %Z\" -d \"+1 day\"') }}"  
# 10am tomorrow
    products: "{{ satellite_products | map(attribute='name') | list }}"
    state: present
