---
# so very many to include
# https://github.com/nickhardiman/ansible-playbook-aap-lab/blob/main/aap-lab-playbook%F0%9F%98%8E.yml

# - ansible.builtin.import_playbook: playbooks/satellite-content-add.yml
# - ansible.builtin.import_playbook: playbooks/satellite-infrastructure-add.yml
# - ansible.builtin.import_playbook: playbooks/satellite-configure-add.yml

# https://satellite/ > Administer > Settings > Content > Default HTTP Proxy
# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/settings

# Vile workaround for crap var scope and passing
- name: Include vars from satellite config directory
  ansible.builtin.include_vars:
    dir: satellite-config
    ignore_files: []
    extensions: ["yml"]

- name: "Create proxy config 'gateway' for http://{{ server_proxy_fqdn }}:{{ server_proxy_port }}"
  redhat.satellite.http_proxy:
    name: gateway
    url: "http://{{ server_proxy_fqdn }}:{{ server_proxy_port }}"
    server_url:   "{{ satellite_server_url }}"
    username:     "{{ satellite_username }}"
    password:     "{{ satellite_password }}"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"
    state: present

# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/$ROLE
# $ROLE is settings, manifest, repositories, lifecycle_environments, etc. 
- name: "Add roles that don't need extra vars"
  ansible.builtin.include_role:
    name: "{{ l_role }}"
  loop:
    - redhat.satellite.settings                # see variable satellite_settings
    - redhat.satellite.manifest                # see variables satellite_manifest_*
    - redhat.satellite.repositories            # see variable satellite_products
    - redhat.satellite.lifecycle_environments  # see variable satellite_lifecycle_environments
    - redhat.satellite.content_views           # see variables satellite_organization and satellite_content_views
    - redhat.satellite.content_view_publish    # also uses satellite_content_views
    - redhat.satellite.activation_keys         # see variable satellite_activation_keys
    - redhat.satellite.domains
    - redhat.satellite.subnets
    - redhat.satellite.hostgroups
  loop_control:
    loop_var: l_role
