---

# a simpler version of the far superior
# https://github.com/sscheib/ansible_satellite
# overhaul of my previous attempt 
# https://github.com/nickhardiman/ansible-playbook-aap-lab/blob/main/playbooks/satellite-install-installer.yml

- name: Change settings
  ansible.builtin.include_tasks: settings.yml
- name: Manage repo content
  ansible.builtin.include_tasks: content.yml
- name: Set up host creationjs
  ansible.builtin.include_tasks: provision.yml
