---
# !!! not idempotent
# may get upset at manifest import
# may publish new content views

# a simpler version of the far superior
# https://github.com/sscheib/ansible_satellite
# overhaul of my previous attempt 
# https://github.com/nickhardiman/ansible-playbook-aap-lab/blob/main/playbooks/satellite-install-installer.yml

# Vile workaround for crap var scope and passing
- name: Include vars from satellite config directory
  ansible.builtin.include_vars:
    dir: satellite-config
    ignore_files: []
    extensions: ["yml"]

# - name: Change settings
#   ansible.builtin.include_tasks: settings.yml
# - name: Get repo content
#   ansible.builtin.include_tasks: content_sync.yml
# - name: Manage repo content
#   ansible.builtin.include_tasks: content_config.yml
- name: Set up host creation
  ansible.builtin.include_tasks: provision.yml
