---

- name: "Create proxy config 'gateway' for http://{{ server_proxy_fqdn }}:{{ server_proxy_port }}"
  redhat.satellite.http_proxy:
    name: gateway
    url: "http://{{ server_proxy_fqdn }}:{{ server_proxy_port }}"
    server_url:   "{{ satellite_server_url }}"
    username:     "{{ satellite_username }}"
    password:     "{{ satellite_password }}"
    organizations:
      - "{{ satellite_organization }}"
    locations:
      - "{{ satellite_location }}"
    state: present

# https://console.redhat.com/ansible/automation-hub/collections/published/redhat/satellite/documentation/role/$ROLE
# $ROLE is settings, manifest, repositories, lifecycle_environments, etc. 
- name: "Add roles that don't need extra vars"
  ansible.builtin.include_role:
    name: "{{ l_role }}"
  loop:
    - redhat.satellite.settings                # see variable satellite_settings
  loop_control:
    loop_var: l_role
