---
# many values from ~/vault-credentials.yml
#
# CaC
# https://github.com/sscheib/ansible_satellite/blob/main/host_vars/satellite.office.int.scheib.me/00b_register_satellite.yml
# satellite installer
# https://docs.redhat.com/en/documentation/red_hat_satellite/6.18/html-single/installing_satellite_server_in_a_connected_network_environment/index#configuring-repositories_satellite
# X509 server certificate
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.15/html-single/installing_satellite_server_in_a_connected_network_environment/index#creating-a-custom-ssl-certificate_satellite

install_app_rhc_repositories:
  - name: 'rhel-9-for-x86_64-baseos-rpms'
    state: 'enabled'
  - name: 'rhel-9-for-x86_64-appstream-rpms'
    state: 'enabled'
  - name: 'satellite-6.18-for-rhel-9-x86_64-rpms'
    state: 'enabled'
  - name: 'satellite-maintenance-6.18-for-rhel-9-x86_64-rpms'
    state: 'enabled'
  - name: 'satellite-utils-6.18-for-rhel-9-x86_64-rpms'
    state: 'enabled'
# RHEL release to set in subscription-manager
install_app_rhc_release: 9

install_app_satellite_installer_scenario: satellite
install_app_satellite_installer_package: 'satellite-installer'
install_app_satellite_installer_verbose: true
#
# install_app_satellite_installer_options
# translates to a CLI command like this.
# If making changes to the command, running manually is a good idea.
# Errors are a little easier to spot in the terminal output.
# Most messages are written to the activity log at 
# /var/log/foreman-installer/satellite.log
#
# satellite-installer  \
#   --scenario satellite  \
#   --verbose  \
#   --tuning  development  \
#   ...(many more options)...
#   --enable-foreman-plugin-discovery  \
#   --enable-foreman-proxy-plugin-discovery  \
#   --enable-foreman-plugin-remote-execution-cockpit
#
# https://docs.redhat.com/en/documentation/red_hat_satellite/6.18/html-single/integrating_provisioning_infrastructure_services/index#enabling-the-installer-managed-dns-service

install_app_satellite_installer_options:
  - '--tuning  development'  # complain but don't stop install
  - '--foreman-initial-admin-username admin'  # Initial user to create
  - "--foreman-initial-admin-password '{{ default_password }}'"  # Password for the initial user
  - '--certs-server-cert    /etc/pki/tls/certs/{{ fqdn }}.pem'  # Satellite certificate (public key) to use
  - '--certs-server-key     /etc/pki/tls/private/{{ fqdn }}.key'  # Satellite private key to use
  - '--certs-server-ca-cert /etc/pki/ca-trust/source/anchors/{{ ca_fqdn }}-cert.pem'  # CA bundle to use
  - '--puppet-runmode none'  # No Puppet, please
  - '--foreman-proxy-dhcp           true'  # Satellite should manage the DHCP
  - '--foreman-proxy-dhcp-managed   true '
  - '--foreman-proxy-dhcp-gateway   "{{ lab_net_prefix }}.1" '
  - '--foreman-proxy-dhcp-nameservers "{{ lab_net_prefix }}.5" '
  - '--foreman-proxy-dhcp-range     "{{ lab_net_prefix }}.100 {{ lab_net_prefix }}.199" '
  - '--foreman-proxy-dhcp-server    "{{ lab_net_prefix }}.5" '
  - '--foreman-proxy-dns            true'
  - '--foreman-proxy-dns-provider   nsupdate'
  - '--foreman-proxy-dns-managed    true'
  - '--reset-foreman-proxy-dns-server'
  # - '--foreman-proxy-dns-zone       "{{ lab_domain }}"'
  # - '--foreman-proxy-dns-reverse    "{{ lab_domain_reverse }}"'
  - '--foreman-proxy-dns-forwarders "{{ lab_net_prefix }}.3"'  # gateway
#  - '--foreman-proxy-dns-server     "127.0.0.1"'
  - '--foreman-proxy-http           true'     # UEFI HTTP boot provisioning
  - '--foreman-proxy-httpboot       true'
  - '--foreman-proxy-tftp           true'  # Satellite should provide TFTP
  - '--foreman-proxy-tftp-managed   true'
  - '--foreman-proxy-tftp-listen-on both'  # We want to serve both HTTP and HTTPS
  - '--foreman-proxy-tftp-servername "{{ lab_net_prefix }}.5"'
  - '--foreman-proxy-templates      true'  # Enable the builtin Template Capsule
  - '--enable-foreman-plugin-discovery'  # Whether to enable Satellite discovery
  - '--enable-foreman-proxy-plugin-discovery'  # Whether to enable Satellite discovery
  - '--enable-foreman-plugin-remote-execution-cockpit'  # web console on provisioned hosts

