---

# a simpler version of the far superior
# https://github.com/sscheib/ansible_satellite
# overhaul of my previous attempt 
# https://github.com/nickhardiman/ansible-playbook-aap-lab/blob/main/playbooks/satellite-install-installer.yml

- name: Install installer
  ansible.builtin.include_tasks: install_installer.yml
- name: Run installer
  ansible.builtin.include_tasks: run_installer.yml
