# yet another defaults file
#
# home network
home_network: "192.168.1.0/24"
home_domain: home

# lab public network
public_net_short_name: public
public_libvirt_name: "net{{ public_net_short_name }}"
public_nmcli_name: "bridge-{{ public_net_short_name }}"
public_bridge_name: "br{{ public_net_short_name }}"
public_mac_prefix: "52:54:00:00"

# lab private network
lab_net_short_name:    lab
lab_net_prefix:        "192.168.134"
lab_mac_prefix:        "52:54:00:03"
lab_libvirt_name:   "net{{ lab_net_short_name }}"
lab_nmcli_name: "bridge-{{ lab_net_short_name }}"
lab_bridge_name:     "br{{ lab_net_short_name }}"
lab_bridge_mac:        "{{ lab_mac_prefix }}:00:01"
lab_bridge_ip_cidr:    "{{ lab_net_prefix }}.1/24"
lab_domain: silvan.uk
# lab_domain:            "{{ lab_net_short_name }}.example.com"
# DNS Zone names in IPA Server
lab_domain_forward:    "{{ lab_domain }}"
# Satellite does not handle the trailing full stop/period/dot ".".
# lab_domain_reverse:    "134.168.192.in-addr.arpa."
lab_domain_reverse:    "134.168.192.in-addr.arpa"

# proxy
# useful for RHSM registration, package downloads
server_proxy_hostname: "gateway"
server_proxy_fqdn: "{{ server_proxy_hostname }}.{{ lab_domain }}"
server_proxy_port: 3128
